name: Deploy

inputs:
  # SSH
  host:
    required: true
  username:
    required: true
  port:
    required: true
  ssh-private-key:
    required: true

  # Docker
  image-name:
    required: true
  server-port:
    required: true
  container-name:
    required: true
  application-port:
    required: true

  # App
  mongo-uri:
    required: true
  our-env:
    required: true

  whitelisted-emails:
    required: true
  auth-jwt-secret:
    required: true

  admin-secret-admin-key:
    required: true

  internal-telegram-bot-token:
    required: true

  google-client-id:
    required: true
  google-client-secret:
    required: true

  better-stack-source-token:
    required: false
  better-stack-source-endpoint:
    required: false

  mail-user:
    required: true
  mail-password:
    required: true

runs:
  using: "composite"
  steps:
    - name: Update image inside VPS
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ inputs.host }}
        USERNAME: ${{ inputs.username }}
        PORT: ${{ inputs.port }}
        KEY: ${{ inputs.ssh-private-key }}
        script: |
          docker pull ${{ inputs.image-name }}
          docker rm -f ${{ inputs.container-name }}
          docker run -d \
          -p ${{ inputs.server-port }}:${{ inputs.application-port }} \
          --restart=always \
          --name ${{ inputs.container-name }} \
          -e MONGO_URI=${{ inputs.mongo-uri }} \
          -e OUR_ENV=${{ inputs.our-env }} \
          -e WHITELISTED_EMAILS=${{ inputs.whitelisted-emails }} \
          -e AUTH_JWT_SECRET=${{ inputs.auth-jwt-secret }} \
          -e ADMIN_SECRET_ADMIN_KEY=${{ inputs.admin-secret-admin-key }} \
          -e INTERNAL_TELEGRAM_BOT_TOKEN=${{ inputs.internal-telegram-bot-token }} \
          -e GOOGLE_CLIENT_ID=${{ inputs.google-client-id }} \
          -e GOOGLE_CLIENT_SECRET=${{ inputs.google-client-secret }} \
          -e BETTER_STACK_SOURCE_TOKEN=${{ inputs.better-stack-source-token }} \
          -e BETTER_STACK_SOURCE_ENDPOINT=${{ inputs.better-stack-source-endpoint }} \
          -e MAIL_USER=${{ inputs.mail-user }} \
          -e MAIL_PASSWORD=${{ inputs.mail-password }} \
          ${{ inputs.image-name }}
